# App
spring.application.name=coc-dashboard

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/coc_dashboard
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

#Coc API
coc.api.token = ${COC_API_TOKEN}
}
coc.api.base-url = https://api.clashofclans.com/v1

#Actuator
management.endpoints.web.exposure.include=health, info
#management.endpoint.health.show-details=always

#Server
server.port=8080

